package com.zhou.ssm.model;

public class Tbladmin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbladmin.userID
     *
     * @mbggenerated Tue Apr 18 14:54:15 CST 2017
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbladmin.userPassword
     *
     * @mbggenerated Tue Apr 18 14:54:15 CST 2017
     */
    private String userpassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbladmin.userRole
     *
     * @mbggenerated Tue Apr 18 14:54:15 CST 2017
     */
    private Integer userrole;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbladmin.userID
     *
     * @return the value of tbladmin.userID
     *
     * @mbggenerated Tue Apr 18 14:54:15 CST 2017
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbladmin.userID
     *
     * @param userid the value for tbladmin.userID
     *
     * @mbggenerated Tue Apr 18 14:54:15 CST 2017
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbladmin.userPassword
     *
     * @return the value of tbladmin.userPassword
     *
     * @mbggenerated Tue Apr 18 14:54:15 CST 2017
     */
    public String getUserpassword() {
        return userpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbladmin.userPassword
     *
     * @param userpassword the value for tbladmin.userPassword
     *
     * @mbggenerated Tue Apr 18 14:54:15 CST 2017
     */
    public void setUserpassword(String userpassword) {
        this.userpassword = userpassword == null ? null : userpassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbladmin.userRole
     *
     * @return the value of tbladmin.userRole
     *
     * @mbggenerated Tue Apr 18 14:54:15 CST 2017
     */
    public Integer getUserrole() {
        return userrole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbladmin.userRole
     *
     * @param userrole the value for tbladmin.userRole
     *
     * @mbggenerated Tue Apr 18 14:54:15 CST 2017
     */
    public void setUserrole(Integer userrole) {
        this.userrole = userrole;
    }
}