package com.zhou.ssm.model;

import java.util.Date;

public class Tblroom {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tblroom.id
     *
     * @mbggenerated Tue Apr 18 14:54:15 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tblroom.room
     *
     * @mbggenerated Tue Apr 18 14:54:15 CST 2017
     */
    private Integer room;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tblroom.rLender
     *
     * @mbggenerated Tue Apr 18 14:54:15 CST 2017
     */
    private String rlender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tblroom.rDate
     *
     * @mbggenerated Tue Apr 18 14:54:15 CST 2017
     */
    private Date rdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tblroom.beginTime
     *
     * @mbggenerated Tue Apr 18 14:54:15 CST 2017
     */
    private Date begintime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tblroom.endTime
     *
     * @mbggenerated Tue Apr 18 14:54:15 CST 2017
     */
    private Date endtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tblroom.id
     *
     * @return the value of tblroom.id
     *
     * @mbggenerated Tue Apr 18 14:54:15 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tblroom.id
     *
     * @param id the value for tblroom.id
     *
     * @mbggenerated Tue Apr 18 14:54:15 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tblroom.room
     *
     * @return the value of tblroom.room
     *
     * @mbggenerated Tue Apr 18 14:54:15 CST 2017
     */
    public Integer getRoom() {
        return room;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tblroom.room
     *
     * @param room the value for tblroom.room
     *
     * @mbggenerated Tue Apr 18 14:54:15 CST 2017
     */
    public void setRoom(Integer room) {
        this.room = room;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tblroom.rLender
     *
     * @return the value of tblroom.rLender
     *
     * @mbggenerated Tue Apr 18 14:54:15 CST 2017
     */
    public String getRlender() {
        return rlender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tblroom.rLender
     *
     * @param rlender the value for tblroom.rLender
     *
     * @mbggenerated Tue Apr 18 14:54:15 CST 2017
     */
    public void setRlender(String rlender) {
        this.rlender = rlender == null ? null : rlender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tblroom.rDate
     *
     * @return the value of tblroom.rDate
     *
     * @mbggenerated Tue Apr 18 14:54:15 CST 2017
     */
    public Date getRdate() {
        return rdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tblroom.rDate
     *
     * @param rdate the value for tblroom.rDate
     *
     * @mbggenerated Tue Apr 18 14:54:15 CST 2017
     */
    public void setRdate(Date rdate) {
        this.rdate = rdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tblroom.beginTime
     *
     * @return the value of tblroom.beginTime
     *
     * @mbggenerated Tue Apr 18 14:54:15 CST 2017
     */
    public Date getBegintime() {
        return begintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tblroom.beginTime
     *
     * @param begintime the value for tblroom.beginTime
     *
     * @mbggenerated Tue Apr 18 14:54:15 CST 2017
     */
    public void setBegintime(Date begintime) {
        this.begintime = begintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tblroom.endTime
     *
     * @return the value of tblroom.endTime
     *
     * @mbggenerated Tue Apr 18 14:54:15 CST 2017
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tblroom.endTime
     *
     * @param endtime the value for tblroom.endTime
     *
     * @mbggenerated Tue Apr 18 14:54:15 CST 2017
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }
}