package com.zhou.ssm.dao;

import com.zhou.ssm.model.Tblnews;
import com.zhou.ssm.model.TblnewsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface TblnewsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblnews
     *
     * @mbggenerated Mon Apr 03 19:35:45 CST 2017
     */
    int countByExample(TblnewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblnews
     *
     * @mbggenerated Mon Apr 03 19:35:45 CST 2017
     */
    int deleteByExample(TblnewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblnews
     *
     * @mbggenerated Mon Apr 03 19:35:45 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblnews
     *
     * @mbggenerated Mon Apr 03 19:35:45 CST 2017
     */
    int insert(Tblnews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblnews
     *
     * @mbggenerated Mon Apr 03 19:35:45 CST 2017
     */
    int insertSelective(Tblnews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblnews
     *
     * @mbggenerated Mon Apr 03 19:35:45 CST 2017
     */
    List<Tblnews> selectByExampleWithBLOBs(TblnewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblnews
     *
     * @mbggenerated Mon Apr 03 19:35:45 CST 2017
     */
    List<Tblnews> selectByExample(TblnewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblnews
     *
     * @mbggenerated Mon Apr 03 19:35:45 CST 2017
     */
    Tblnews selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblnews
     *
     * @mbggenerated Mon Apr 03 19:35:45 CST 2017
     */
    int updateByExampleSelective(@Param("record") Tblnews record, @Param("example") TblnewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblnews
     *
     * @mbggenerated Mon Apr 03 19:35:45 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") Tblnews record, @Param("example") TblnewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblnews
     *
     * @mbggenerated Mon Apr 03 19:35:45 CST 2017
     */
    int updateByExample(@Param("record") Tblnews record, @Param("example") TblnewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblnews
     *
     * @mbggenerated Mon Apr 03 19:35:45 CST 2017
     */
    int updateByPrimaryKeySelective(Tblnews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblnews
     *
     * @mbggenerated Mon Apr 03 19:35:45 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(Tblnews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblnews
     *
     * @mbggenerated Mon Apr 03 19:35:45 CST 2017
     */
    int updateByPrimaryKey(Tblnews record);
    List<Tblnews> selectAll();
}