package com.zhou.ssm.dao;

import com.zhou.ssm.model.Tblpaper;
import com.zhou.ssm.model.TblpaperExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface TblpaperMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblpaper
     *
     * @mbggenerated Mon Apr 03 19:35:45 CST 2017
     */
    int countByExample(TblpaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblpaper
     *
     * @mbggenerated Mon Apr 03 19:35:45 CST 2017
     */
    int deleteByExample(TblpaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblpaper
     *
     * @mbggenerated Mon Apr 03 19:35:45 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblpaper
     *
     * @mbggenerated Mon Apr 03 19:35:45 CST 2017
     */
    int insert(Tblpaper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblpaper
     *
     * @mbggenerated Mon Apr 03 19:35:45 CST 2017
     */
    int insertSelective(Tblpaper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblpaper
     *
     * @mbggenerated Mon Apr 03 19:35:45 CST 2017
     */
    List<Tblpaper> selectByExample(TblpaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblpaper
     *
     * @mbggenerated Mon Apr 03 19:35:45 CST 2017
     */
    Tblpaper selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblpaper
     *
     * @mbggenerated Mon Apr 03 19:35:45 CST 2017
     */
    int updateByExampleSelective(@Param("record") Tblpaper record, @Param("example") TblpaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblpaper
     *
     * @mbggenerated Mon Apr 03 19:35:45 CST 2017
     */
    int updateByExample(@Param("record") Tblpaper record, @Param("example") TblpaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblpaper
     *
     * @mbggenerated Mon Apr 03 19:35:45 CST 2017
     */
    int updateByPrimaryKeySelective(Tblpaper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblpaper
     *
     * @mbggenerated Mon Apr 03 19:35:45 CST 2017
     */
    int updateByPrimaryKey(Tblpaper record);
    List<Tblpaper> selectAll();
}