package com.zhou.ssm.dao;

import com.zhou.ssm.model.Tblroom;
import com.zhou.ssm.model.TblroomExample;

import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface TblroomMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblroom
     *
     * @mbggenerated Mon Apr 03 19:35:45 CST 2017
     */
    int countByExample(TblroomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblroom
     *
     * @mbggenerated Mon Apr 03 19:35:45 CST 2017
     */
    int deleteByExample(TblroomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblroom
     *
     * @mbggenerated Mon Apr 03 19:35:45 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblroom
     *
     * @mbggenerated Mon Apr 03 19:35:45 CST 2017
     */
    int insert(Tblroom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblroom
     *
     * @mbggenerated Mon Apr 03 19:35:45 CST 2017
     */
    int insertSelective(Tblroom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblroom
     *
     * @mbggenerated Mon Apr 03 19:35:45 CST 2017
     */
    List<Tblroom> selectByExample(TblroomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblroom
     *
     * @mbggenerated Mon Apr 03 19:35:45 CST 2017
     */
    Tblroom selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblroom
     *
     * @mbggenerated Mon Apr 03 19:35:45 CST 2017
     */
    int updateByExampleSelective(@Param("record") Tblroom record, @Param("example") TblroomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblroom
     *
     * @mbggenerated Mon Apr 03 19:35:45 CST 2017
     */
    int updateByExample(@Param("record") Tblroom record, @Param("example") TblroomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblroom
     *
     * @mbggenerated Mon Apr 03 19:35:45 CST 2017
     */
    int updateByPrimaryKeySelective(Tblroom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblroom
     *
     * @mbggenerated Mon Apr 03 19:35:45 CST 2017
     */
    int updateByPrimaryKey(Tblroom record);
    List<Tblroom> selectAll(int i);
    List<Tblroom> selectRoom(String id);
    List<Tblroom> selectDate(Date date,int i);
}